### ISSUE TITLE
Bump Windows + Eclipse IDE setup instruction dependency versions

### ISSUE THREAD

**Issue by wbkboyer** [graph-algorithms/edge-addition-planarity-suite#103]
The instructions in `README.md` from commit [b4063b](https://github.com/graph-algorithms/edge-addition-planarity-suite/blob/b4063bf68d2ac6788f0c1eec42e617d4d269dbb5/README.md) (soon to be moved into the [2. Dev Setup](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/2.-Dev-Setup) wiki page) reference installing old versions of the JDK, Eclipse, and MinGW-32 (see #102 ).

Let's bump these versions and see if we're still able to compile and debug in Eclipse, then update the instructions to capture the updated steps!

**Comment by john-boyer-phd** [comment]
Now that we have VS Code in our pockets for over a year now, we're not going back! So we're going to close this issue by sunsetting the Eclipse dev environment.
