### ISSUE TITLE
Fix defect that `K_{3,3}` search doesn't find a `K_{3,3}` homeomorph in the 6-vertex 13-edge graph with G6 encoding of `EV~w`

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#105]
On the graph with the adjacency list format given below (corresponding to `EV~w` in the G6 format), the `K_{3,3}` homeomorph search returns a result indicating that the graph does not contain a subgraph homeomorphic to `K_{3,3}`:

```
N=6
0: 2 3 4 5 -1
1: 3 4 5 -1
2: 0 3 4 5 -1
3: 0 1 2 4 5 -1
4: 0 1 2 3 5 -1
5: 0 1 2 3 4 -1
```
However, it was determined through edge deletion analysis (by removing the edge `(0, 2)`) that this graph does contain a subgraph homeomorphic to `K_{3,3}`. The goal of this issue is to find and fix the defect so that the `K_{3,3}` homeomorph search does find a  subgraph homeomorphic to `K_{3,3}` given the graph  above.

To simplify debugging, the 1-based version of this graph is:

```
N=6
1: 3 4 5 6 0
2: 4 5 6 0
3: 1 4 5 6 0
4: 1 2 3 5 6 0
5: 1 2 3 4 6 0
6: 1 2 3 4 5 0
```

**Comment by john-boyer-phd** [comment]
Whether reading the 0-based or 1-based input file, the in-memory data structure is 1-based except if the code is recompiled with the zero-based flag setting. 

The DFS of the graph results in the following depiction (straight edges with with a crossing tickmark for tree edges and curves for back edges):

![DFSBeforeSort_halfsize](https://github.com/user-attachments/assets/cf2632d0-708b-4ae6-9db1-d79ca3a9ce51)

After `gp_SortVertices()` we have this numbering based on DFI, which corresponds to the in-memory data structure presented to the core planarity algorithm and the `K_{3,3}` homeomorph search:

![DFSAfterSort_halfsize](https://github.com/user-attachments/assets/26988c3c-a0cd-48ff-bd63-1581bd98f62a)

**Comment by john-boyer-phd** [comment]
The `K_{3,3}` homeomorph search and the core planarity algorithm operate in the exact same way until a non-planarity condition is discovered. Hence we begin with an analysis of planarity algorithm operations up to the discovery that the input graph is non-planar. The following depiction shows the key operations of the core planarity algorithm up to that point:

![AlgorithmProcessing_halfsize](https://github.com/user-attachments/assets/bdf3a9f5-b2bb-4a06-a98b-d3e7aa631358)

**TBD:**  Step by step description of all diagram elements leading up to the non-planarity condition discovered in step `v=2` on the bottom row of the diagram.

Once a non-planarity condition corresponding to a `K_5` homeomorph is discovered, as is the case with this graph, only then does the `K_{3,3}` homeomorph search perform three additional tests to determine whether a `K_{3,3}` homeomorph is entangled with the `K_5` homeomorph. The `K_5` homeomorph pattern is called `E` and those additional tests are characterized by the diagrams `E5`, `E6`, and `E7` in the JGAA subgraph homeomorphism paper (see Figure 9e for pattern E and Figure 11abc for patterns `E5`, `E6`, and `E7`). 

 **TBD:** More info about how the depiction at the bottom right maps to pattern `E` and more specifically pattern `E5`.

**Comment by john-boyer-phd** [comment]
The method `_TestForZtoWPath()` in `graphK33Search.c` is reusing the xy-path that was marked by the core planarity algorithm, but the pattern E5 is intended to be "symmetric with non-planarity minor D" ([p. 402](https://doi.org/10.7155/jgaa.00268)) with the path emanating from the internal vertex z connecting with w below rather than v above. For non-planarity minor D, the closest xy-path is found by hiding the internal edges incident to the target vertex v, i.e., all edges except the two connecting v to the external face, and then traversing the internal proper face starting at the target vertex v (see `_MarkHighestXYPath()`). As shown in the following diagram, the symmetric behavior for E5 is to hide the internal edges of the target vertex w and then traverse the internal proper face starting at the target vertex w. 

![SymmetricApproachNeeded_halfsize](https://github.com/user-attachments/assets/923c1230-3357-4a03-9fdd-f455bf3effa7)

The arc around vertex w signifies hiding of the internal edges. Then, the proper face walk begins at w and makes its way along paths parallel to the inside of the external face path from w to x. Once the proper face walk reaches x, there may be a number of attached components that, when traversed, would lead back to vertex w except that the internal edges of w have been hidden, so instead the proper face walk will make it back to x as many times as needed before finally veering off along the path to the vertex labeled z in the depiction. If there is indeed a z-to-w path (if there is indeed a minor E5 pattern), then that path has been cut off from access to w by hiding its internal edges, but this is OK because at this moment we are simply trying to find the xy-path closest to w and will restore the hidden internal edges once that is done. So, the proper face traversal will travel down that z-to-w path if it exists, but then traverse back up the other side of the path and return to z, then continue on to vertex y.  

We know that the xy-path identified by this method will be connected directly to vertices x and y, and not some lower vertices along the paths between w and x and, respectively, w and y because the test for pattern E4 has already determined that no lower xy-paths exist. Similarly, we know that the closest xy-path to w attaches to vertices x and y, and not some higher vertices along the paths between x and v and, respectively, y and v because the test for pattern C has already determined that no xy-paths with high points of attachment exist. If C or E4 had existed, then a subgraph homeomorphic to `K_{3,3}` would have already been isolated before running the test for E5.

We also know that the xy-path closest to w, obtained in the manner above and symmetric to how the xy-path for pattern D is obtained, is the the only xy-path that could possibly have a z-to-w path because the core planarity algorithm at all times maintains _planar embeddings_ of the biconnected components that have been formed by the edges it has managed to successfully embed without being blocked.  No xy-path farther from w could possibly have a z-to-w path because the z-to-w path would cross the closest xy-path we are identifying, which would violate the planarity of the containing bicomp.

Once the xy-path closest to w had been identified, the hidden internal edges are restored. Then, the z-to-w path can be identified in a manner symmetric with how the z-to-v path is found for pattern D. This is done by `_MarkZtoRPath()` in `graphNonplanar.c`, where R signifies a root copy (virtual vertex copy) of vertex v. The symmetric method for pattern E5 is   `_TestForZtoWPath()` in `graphK33Search.c`, which was mentioned at the top of this comment.

**Comment by wbkboyer** [comment]
See branch on my fork of EAPS, [`Issue105-ReproducingK33SearchE5CaseDefect`](https://github.com/wbkboyer/edge-addition-planarity-suite/tree/Issue105-ReproducingK33SearchE5CaseDefect), for reproduction of this bug meant for testing EDA fidelity (i.e. detects the same invalid `OK` results).
