### ISSUE TITLE
Story in Epic 10: Make man Page and help updates for .g6 format addition

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#33]
Part of Epic #10. All variations of the new `-t` command-line parameter must be added to the man page and the help message.

Under Linux, do a `sudo make install` based on the compressed tarball produced by the make distribution process, and then verify that the man page for planarity shows the expected output.

**Comment by wbkboyer** [comment]
Look to #12 to see how the manpage is updated.
