### ISSUE TITLE
Remediate Function Pointer Warnings from Mac clang Compiler

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#40]
This project provides algorithmic extensibility of the planarity-related algorithms by using functions pointers to make virtual those functions that may need to be overloaded. Ideally, we would like to simply include the parameter lists of the virtual functions in their function pointer declarations. However, this causes compiler errors for many compilers including _gcc_. 

Recently, we have been adding support for _clang_ on the Mac. However, it produces 92 compiler warnings, one per invocation of a function via function pointer. The warnings indicate that such function invocations without parameter lists is deprecated. Online documentation suggests that support has been removed in C23. Despite producing the warnings, _clang_ also produces compiler errors if the parameter lists are added to the function pointer declarations. 

We need a method to eliminate the _clang_ warnngs while not introducing any compilation errors for previously supported compilers including _gcc_. Preferably, the new declaration method will also be compatible with C23 compilation.

**Comment by wbkboyer** [comment]
The warning messages are of the form:
```
passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C23 [-Wdeprecated-non-prototype]
```

It would be interesting to see the overlap with the warnings induced by adding `-Wall` to the invocation of MinGW `gcc`, or `/Wall` to the invocation of MSVC `cl` (See [MSVC - Compiler option warning level](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170) for alternative flags) in `tasks.json`, as outlined in #96 

There's some discussion on this `zlib` issue that might point to a solution: [Functions without prorotypes cause -Wstrict-prototypes warnings](https://github.com/madler/zlib/issues/633)

Function pointers are declared in `c/graphLib/extensionSystem/graphFunctionTable.h`, then initialized in `_InitFunctionTable()` of `c/graphLib/graphUtils.c`, which is called when we `gp_New()` and also when we `gp_FreeExtensions()` (Called when we `_ClearGraph()` or `gp_CopyExtensions()`). I can't seem to find instances where these function pointers are overridden within the graph algorithm extensions, only observe where we call these functions.

The next steps would be to create a small sample project that uses function pointers as we do and to use this as a sandbox for possible solutions; then, once we resolve the warnings in the sample project, work would need to be done to extend the solution to the `edge-addition-planarity-suite` project.

**Comment by wbkboyer** [comment]
Related to #118
