### ISSUE TITLE
Issue 62 - Write six separate scripts to sequentially invoke the release version of `planarity` on all 55 11-vertex graphs for each algorithm (pdo234)

### ISSUE THREAD

**Issue by wbkboyer** [graph-algorithms/edge-addition-planarity-suite#62]
Write six separate scripts for each algorithm (pdo234) to invoke the release version of `planarity` in sequence to test all graphs with the script's algorithm for each of the 55 11-vertex `graph6` files. Make the output file names indicate the input filenames followed by a suffix of `.C.out.txt` where C is the algorithm identifier (p, d, o, 2, 3, or 4). Check the six scripts into the `Test Support` directory. In six separate shells, run each of the six scripts on the 11-vertex graphs.

**Comment by john-boyer-phd** [comment]
This was closed by PR #63 but my squash merge comment didn't correctly trigger the close operation, so closing manually.
