### ISSUE TITLE
EPIC: Automate validity testing of `OK` results from homeomorph search algorithm implementations

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#80]
The test table generator program (from #65) creates a table that shows the number of `OK` and `NONEMBEDDABLE` results (and other summary data) across all of the edge-specific files for a given vertex order.

The goal of the desired program for this issue is to import and improve upon the logic of the original test table generator to:
* create a table with an extra column indicating the number of `invalid OK` results, in total and per edge count based on performing edge deletion analysis (from #77 and #79) on all graphs reported to be `OK` by the homeomorphic subgraph search algorithm being tests (`K_{3,3}`, `K_{2,3}`, and `K_4`).
* create an output `.g6` file per edge count that contains all graphs with `invalid OK` results.

This program will need to name the output table file and the `.g6` files according to the algorithm being run as well as the graph order (`N` value). 

This program will need to be run on the outputs of `geng`, canonical `geng`, and canonical `makeg`. 

This program should be initially run on vertex orders `N=`6 to 10 inclusive to get a baseline of current invalid OK results before we start fixing bugs. The contents of the output tables for each algorithm and for `N=`6 to 10 (15 tables) should be preserved, such as by checking them in.

After this epic is done and the baseline recorded, the bugs will be fixed, and the tables will be updated, until the number of `invalid OK` results is uniformly zero).

**Comment by wbkboyer** [comment]
See #107 to see this script at work. However, further work must be done (#108) to use this script for larger `N` due to what appears to be a Windows system-level memory leak for the Page Table Entries of terminated processes not being cleaned up.
