### ISSUE TITLE
Create a wiki page for all Test Support modules

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#88]
There should be a wiki page that explains the use cases/workflows, expected inputs, and forms of the outputs of the various tools. A lot of information can be harvested from the helpful help strings in the tools, but this wiki page can include more English that lays out the context, workflow thinking, and how all the pieces are intended to fit together. The current page for the memory checker(s) could go in as a section of this page.

**Comment by wbkboyer** [comment]
@john-boyer-phd The first draft of the [Test Support](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/Test-Support) wiki page is ready for review 🎉

**Comment by john-boyer-phd** [comment]
> @john-boyer-phd The first draft of the [Test Support](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/Test-Support) wiki page is ready for review 🎉

Looks fantastic. I made some very minor tweaks to the section titles to make the table of contents lay out better. However, I noticed that this put my name at the top of the page as the last to edit. Therefore, the only other change I'd like is one that I ask you to add so that your name goes back up there :-) It is this: In the Edge Deletion Analyses section, you state that the question we asked is "for each of K_{3, 3} search, K_{2, 3} search, and K_4 search, how many graphs are erroneously reported as not containing a subgraph homeomorphic to the target graph?" It would be better if you could please word it as this: "for each of K_{3, 3} search, K_{2, 3} search, and K_4 search, how many graphs can we detect by edge deletion analysis are erroneously reported as not containing a subgraph homeomorphic to the target graph?" 

Otherwise, I agree that it is reading so well now that it isn't really necessary to pull out the beginnings of each section in an overview. Because you arranged content into collapsible sections, it reads really well just scanning through like it is now. So, we can close this issue during the meeting tomorrow, after you make the tweak above.
