### ISSUE TITLE
EPIC: Appropriately handling the inclusion of default configuration files in source control

### ISSUE THREAD

**Issue by wbkboyer** [graph-algorithms/edge-addition-planarity-suite#89]
While writing the section [Automating memory checking on MacOS using `leaks`](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/3.-Test-Support#automating-memory-checking-on-macos-using-leaks) of the [3. Test Support](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/3.-Test-Support) wiki page, the issue of how to handle the inclusion of default files in source control arose: in #59 , I added the `TestSupport/planaritytesting/leaksorchestrator/planarity_leaks_config.ini` file (generated by the `planarity_leaks_config_manager.py`) to source control, and then added a corresponding line to `.gitignore`, ([erroneously](https://git-scm.com/docs/gitignore#_notes)) assuming that even if a file was tracked in source control, the `.gitignore` would ensure that no changes could be made to the file without first changing the `.gitignore`.

After observing that the behaviour didn't match my expectation, I did some more investigation and arrived at an intermediate solution: instructing users to locally run [`git update-index --assume-unchanged`](https://git-scm.com/docs/git-update-index#Documentation/git-update-index.txt---no-assume-unchanged) on the defaults tracked in the repository so that local changes wouldn't appear as candidates to stage unless they actually intended to update the default in the repository (see also [`git update-index` - Using "Assume Unchanged" Bit](https://git-scm.com/docs/git-update-index#_using_assume_unchanged_bit) for justification vs. using `--skip-worktree`)

However, this is not scalable when dealing with multiple default configuration files, and an entirely process-driven approach is prone to user error. [This StackOverflow response](https://stackoverflow.com/a/18571577/5456879) helps to inform a solution:

1. Create a directory containing default configuration files to be tracked in source control,
2. Implement an environment setup script to copy the default configuration files to the correct locations in the user environment:
    * `.vscode/` - `tasks.json`, `launch.json`, and `settings.json`
    * `TestSupport/planaritytesting/` - `.pylintrc` and `leaksorchestrator/planarity_leaks_config.ini`
3. Run `git -rm --cached` for the configuration files currently tracked in version control (especially the `.cproject`, `c/.cproject` and `.project` files)
4. Add those paths in the user development environment to the `.gitignore`
5. Include instructions in `README.md` to run the environment setup script

**Comment by john-boyer-phd** [comment]
One thing we will have to resolve here for the dev env files (the .json files for VSCode and the .cproject file for Eclipse) is that the dev env may be used to clone the project (rather than git command line), so we need to make sure we know and explain the process step(s) between dev env. clone and successful dev env build of the code.

**Comment by john-boyer-phd** [comment]
Now that we have VS Code in our pockets for over a year now, we're not going back! We're going to address the Eclipse project issue by sunsetting the Eclipse dev environment. So, let's just remove the Eclipse project file but don't add it as something that needs a template to be copied after git cloning.
