### ISSUE TITLE
Write updated development environment setup instructions

### ISSUE THREAD

**Issue by wbkboyer** [graph-algorithms/edge-addition-planarity-suite#99]
The documentation provided in the `edge-addition-planarity-suite`'s `README.md` section on [Setting up a Development Environment](https://github.com/graph-algorithms/edge-addition-planarity-suite?tab=readme-ov-file#setting-up-a-development-environment) has not been updated since before the introduction of VSCode support in #16 and #58 

A new wiki page should be created to house instructions for all supported platforms (i.e. MacOS, Windows, and Debian Linux) for how to:
1. install the requisite build tools,
2. (legacy) install Eclipse 
3. install VSCode and all requisite extensions for both C/C++ and Python development
4. run the development environment setup script from #89

The repository's `README.md` will be updated to link to this wiki page.

**Comment by john-boyer-phd** [comment]
Now that we have VS Code in our pockets for over a year now, we're not going back! So let's focus on VS Code and remove instructions around set up and use of the Eclipse dev environment.

**Comment by wbkboyer** [comment]
Resolved by merging #112 and final updates to [2. Dev Setup](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/2.-Dev-Setup) 🎉
